name: CommandsSerivce CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  buildcommand:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check modified files
      working-directory: ./CommandsService
      id: check_files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}
        
        # Get a list of modified files
        MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        git fsck --full

        # Check if specific directory is modified
        if echo "$MODIFIED_FILES" | grep -q "./CommandsService"; then
          echo "Changes detected in the specified directory."
          echo "::set-output name=directory_changed::true"
        else
          echo "No changes detected in the specified directory."
          echo "::set-output name=directory_changed::false"
        fi
      shell: bash



    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      working-directory: ./CommandsService
      if: steps.check_files.outputs.directory_changed == 'true'
      run: |
        docker build . --file Dockerfile --tag gwadadasol/commandservice:$GITHUB_RUN_ID
        docker push gwadadasol/commandservice:$GITHUB_RUN_ID

  buildplatform:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      working-directory: ./PlatformService
      run: |
        docker build . --file Dockerfile --tag gwadadasol/platformservice:$GITHUB_RUN_ID
        docker push gwadadasol/platformservice:$GITHUB_RUN_ID
