name: CommandsSerivce CI
on:
  push:
    paths:
      - 'CommandsService/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildcommand:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      working-directory: ./CommandsService
      if: steps.check_files.outputs.directory_changed == 'true'
      run: |
        docker build . --file Dockerfile --tag gwadadasol/commandservice:$GITHUB_RUN_ID
        docker push gwadadasol/commandservice:$GITHUB_RUN_ID