name: PlatformSerivce CI

on:
  push:
    paths:
      - 'PlatformService/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildplatform:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      working-directory: ./PlatformService
      run: |
        docker build . --file Dockerfile --tag gwadadasol/platformservice:$GITHUB_RUN_ID
        docker push gwadadasol/platformservice:$GITHUB_RUN_ID
